Fix typos
holoviz/colorcet pull request #91
Opened 2022-09-15 12:43 UTC by kianmeng

Found via `codespell -S ./assets -L als,trough`

2022-09-15 16:00 UTC, jbednar requested changes
Thanks! Some of these are good fixes, and this should be mergeable when it has only those fixes.

2022-09-15 16:00 UTC, jbednar commented on assets/colorcet.m
> +description = 'Cyclic: magenta - red - yellow - blue. Allows four orientations/phase angles to be visulaised.';
Please remove any fixes to the contents of `assets`; these files are mirrors of upstream content whose source is located elsewhere, and we do not want those files to diverge from their source files. Ideally such fixes would be filed at the upstream repo, though I'm not sure where that is (we get the files from https://colorcet.com).

2022-09-15 16:00 UTC, jbednar commented on colorcet/sineramp.py
> +This is set at 12.5 so that from peak to through we have a local feature of
```suggestion
This is set at 12.5 so that from peak to trough we have a local feature of
```

(The original is correct.)

2022-09-16 20:18 UTC, jbednar approved these changes
Perfect, thanks!

2022-09-16 20:18 UTC, merged

2022-09-17 11:07 UTC, kianmeng commented
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: